# Generated by Django 2.1.5 on 2019-02-16 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('paytm', 'Paytm'), ('gpay', 'Google Pay'), ('phope', 'PhonePe'), ('wapp', 'WhatsApp'), ('fmpay', 'FamPay')], default='paytm', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('A', 'Add'), ('P', 'Pay')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], max_length=5),
        ),
    ]
