# Generated by Django 2.1.5 on 2019-02-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190216_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='fam_name',
            new_name='name',
        ),
    ]
