# Generated by Django 2.1.5 on 2019-02-17 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190217_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
